/**
 * Canonical feature registry — source of truth for hub modules.
 * Add new features here; seed/upsert will sync them into MongoDB.
 * Admin can enable/disable, reorder, and override config without code deploys
 * for content-driven modules; new widget keys still need a client renderer.
 */

import { TAMIL_NADU_DISTRICTS } from './tamilNaduDistricts.js';
import { DEFAULT_TN_FUEL_DISTRICTS } from './tamilNaduFuelSlugs.js';

export const FEATURE_CATEGORIES = [
  'utilities',
  'news',
  'classifieds',
  'engagement',
  'community',
  'portal',
];

export const FEATURE_STATUSES = ['live', 'beta', 'coming_soon', 'disabled'];

export const DEFAULT_FEATURES = [
  // Row 1 — live utilities
  {
    key: 'weather',
    name: 'Weather',
    nameTamil: 'வானிலை',
    description: 'Live weather for all Tamil Nadu districts',
    category: 'utilities',
    icon: 'cloud',
    status: 'live',
    enabled: true,
    order: 10,
    row: 1,
    colSpan: 2,
    config: {
      state: 'Tamil Nadu',
      country: 'India',
      timezone: 'Asia/Kolkata',
      unit: 'C',
      defaultDistrict: 'Chennai',
      districts: TAMIL_NADU_DISTRICTS.map(({ district }) => ({ district })),
    },
  },
  {
    key: 'gold_price',
    name: 'Gold Price',
    nameTamil: 'தங்க விலை',
    description: 'Live gold, silver, platinum & diamond rates for Tamil Nadu',
    category: 'utilities',
    icon: 'gold',
    status: 'live',
    enabled: true,
    order: 20,
    row: 1,
    colSpan: 2,
    config: {
      type: 'precious_metals',
      state: 'Tamil Nadu',
      country: 'India',
      auto_update: true,
      diamondGoldRatio: 28,
      items: [
        { type: 'gold', purity: '22K', unit: '1 gram', price: 0, currency: 'INR' },
        { type: 'gold', purity: '24K', unit: '1 gram', price: 0, currency: 'INR' },
        { type: 'silver', unit: '1 gram', price: 0, currency: 'INR' },
        { type: 'diamond', unit: '1 carat', price: 0, currency: 'INR' },
        { type: 'platinum', unit: '1 gram', price: 0, currency: 'INR' },
      ],
    },
  },
  {
    key: 'currency',
    name: 'Currency',
    nameTamil: 'நாணயம்',
    description: 'USD / INR exchange rate',
    category: 'utilities',
    icon: 'currency',
    status: 'live',
    enabled: true,
    order: 30,
    row: 1,
    colSpan: 2,
    config: {
      pair: 'USD / INR',
      rate: 83.42,
      changePercent: 0.15,
    },
  },
  {
    key: 'market',
    name: 'Market',
    nameTamil: 'சந்தை',
    description: 'NIFTY 50 index',
    category: 'utilities',
    icon: 'chart',
    status: 'live',
    enabled: true,
    order: 40,
    row: 1,
    colSpan: 2,
    config: {
      index: 'NIFTY 50',
      value: 22450.3,
      changePercent: 0.85,
    },
  },
  {
    key: 'fuel_price',
    name: 'Fuel Price',
    nameTamil: 'எரிபொருள் விலை',
    description: 'Petrol & diesel rates',
    category: 'utilities',
    icon: 'fuel',
    status: 'live',
    enabled: true,
    order: 50,
    row: 1,
    colSpan: 2,
    config: {
      state: 'Tamil Nadu',
      auto_update: true,
      defaultDistrict: 'Chennai',
      petrol: 102.5,
      diesel: 94.2,
      districts: DEFAULT_TN_FUEL_DISTRICTS.map((district) => ({
        district,
        petrol: 0,
        diesel: 0,
      })),
    },
  },
  {
    key: 'traffic',
    name: 'Traffic',
    nameTamil: 'போக்குவரத்து',
    description: 'City traffic status',
    category: 'utilities',
    icon: 'traffic',
    status: 'live',
    enabled: true,
    order: 60,
    row: 1,
    colSpan: 2,
    config: {
      city: 'Chennai',
      statusLabel: 'Normal',
      detail: 'No major congestion',
      level: 'normal',
    },
  },

  // Row 2 — news + alerts
  {
    key: 'top_news',
    name: 'Top News Today',
    nameTamil: 'இன்றைய முக்கிய செய்திகள்',
    description: 'Featured and latest headlines',
    category: 'news',
    icon: 'news',
    status: 'live',
    enabled: true,
    order: 70,
    row: 2,
    colSpan: 8,
    config: { source: 'articles', limit: 4 },
  },
  {
    key: 'important_today',
    name: 'Important Today',
    nameTamil: 'இன்று முக்கியம்',
    description: 'Deadlines and alerts',
    category: 'news',
    icon: 'alert',
    status: 'live',
    enabled: true,
    order: 80,
    row: 2,
    colSpan: 4,
    config: {},
  },

  // Row 3 — classifieds / services
  {
    key: 'government_notifications',
    name: 'Government Notifications',
    nameTamil: 'அரசு அறிவிப்புகள்',
    description: 'Latest Central and Tamil Nadu government notifications',
    category: 'classifieds',
    icon: 'alert',
    status: 'live',
    enabled: true,
    order: 90,
    row: 3,
    colSpan: 4,
    config: {},
  },
  {
    key: 'matrimony',
    name: 'Matrimony Profiles',
    nameTamil: 'திருமண சுயவிவரங்கள்',
    description: 'Browse verified matrimony profiles',
    category: 'classifieds',
    icon: 'users',
    status: 'live',
    enabled: true,
    order: 100,
    row: 3,
    colSpan: 4,
    config: {},
  },
  {
    key: 'marketplace',
    name: 'Marketplace',
    nameTamil: 'சந்தை',
    description: 'Buy & sell classifieds',
    category: 'classifieds',
    icon: 'cart',
    status: 'live',
    enabled: true,
    order: 110,
    row: 3,
    colSpan: 4,
    config: {},
  },

  // Row 4 — engagement
  {
    key: 'daily_dose',
    name: 'Daily Dose',
    nameTamil: 'தினசரி',
    description: 'Horoscope, quiz, history and more',
    category: 'engagement',
    icon: 'spark',
    status: 'live',
    enabled: true,
    order: 120,
    row: 4,
    colSpan: 7,
    config: {},
  },
  {
    key: 'news_quiz',
    name: 'News Quiz Challenge',
    nameTamil: 'செய்தி வினாடி வினா',
    description: 'Test your knowledge on today’s news',
    category: 'engagement',
    icon: 'trophy',
    status: 'live',
    enabled: true,
    order: 130,
    row: 4,
    colSpan: 5,
    config: {
      cta: 'Start Quiz',
      tagline: "Test your knowledge on today's news!",
    },
  },

  // Row 5 — community
  {
    key: 'local_updates',
    name: 'Local Updates',
    nameTamil: 'உள்ளூர் புதுப்பிப்புகள்',
    description: 'Water, power, metro, AQI',
    category: 'community',
    icon: 'pin',
    status: 'live',
    enabled: true,
    order: 140,
    row: 5,
    colSpan: 4,
    config: { city: 'Chennai' },
  },
  {
    key: 'trending',
    name: 'Trending Now',
    nameTamil: 'டிரெண்டிங்',
    description: 'Popular topics and hashtags',
    category: 'community',
    icon: 'trend',
    status: 'live',
    enabled: true,
    order: 150,
    row: 5,
    colSpan: 4,
    config: {},
  },
  {
    key: 'community_feed',
    name: 'From Our Community',
    nameTamil: 'எங்கள் சமூகத்திலிருந்து',
    description: 'Reader posts and discussions',
    category: 'community',
    icon: 'users',
    status: 'live',
    enabled: true,
    order: 160,
    row: 5,
    colSpan: 4,
    config: {},
  },

  // Portal links — current site features surfaced in hub
  {
    key: 'portal_news',
    name: 'News Portal',
    nameTamil: 'செய்தி போர்டல்',
    description: 'Categories, districts, search, authors',
    category: 'portal',
    icon: 'globe',
    status: 'live',
    enabled: true,
    order: 200,
    row: 6,
    colSpan: 12,
    config: {
      links: [
        { label: 'Home', labelTamil: 'முகப்பு', path: '/' },
        { label: 'Search', labelTamil: 'தேடல்', path: '/search' },
        { label: 'Tamil Nadu', labelTamil: 'தமிழ்நாடு', path: '/tamil-nadu' },
        { label: 'Jobs News', labelTamil: 'வேலைவாய்ப்பு', path: '/jobs' },
        { label: 'About', labelTamil: 'எங்களைப் பற்றி', path: '/about' },
        { label: 'Contact', labelTamil: 'தொடர்பு', path: '/contact' },
      ],
    },
  },
];

export const DEMO_FEATURE_ITEMS = [
  // Important today
  {
    featureKey: 'important_today',
    itemType: 'alert',
    title: 'TNPSC Group 2 Notification',
    titleTamil: 'TNPSC குரூப் 2 அறிவிப்பு',
    icon: 'doc',
    color: '#2563eb',
    meta: { badge: 'Last date: Aug 30' },
    priority: 10,
  },
  {
    featureKey: 'important_today',
    itemType: 'alert',
    title: 'EPF Contribution Due',
    titleTamil: 'EPF பங்களிப்பு நிலுவை',
    icon: 'wallet',
    color: '#16a34a',
    meta: { badge: 'Due: Aug 28' },
    priority: 9,
  },
  {
    featureKey: 'important_today',
    itemType: 'alert',
    title: 'Aadhaar Update Free',
    titleTamil: 'ஆதார் புதுப்பிப்பு இலவசம்',
    icon: 'id',
    color: '#ea580c',
    meta: { badge: 'Till Aug 31' },
    priority: 8,
  },
  {
    featureKey: 'important_today',
    itemType: 'alert',
    title: 'Independence Day Holiday',
    titleTamil: 'சுதந்திர தின விடுமுறை',
    icon: 'flag',
    color: '#dc2626',
    meta: { badge: 'Aug 15' },
    priority: 7,
  },

  // Government Notifications (hub uses live API)

  // Marketplace
  {
    featureKey: 'marketplace',
    itemType: 'market_item',
    title: 'Used iPhone 13',
    image: 'https://picsum.photos/seed/mkt-phone/120/80',
    meta: { price: '₹32,000', location: 'Anna Nagar' },
    priority: 10,
  },
  {
    featureKey: 'marketplace',
    itemType: 'market_item',
    title: 'Royal Enfield Classic 350',
    image: 'https://picsum.photos/seed/mkt-bike/120/80',
    meta: { price: '₹1,45,000', location: 'Velachery' },
    priority: 9,
  },
  {
    featureKey: 'marketplace',
    itemType: 'market_item',
    title: 'Wooden Sofa Set',
    image: 'https://picsum.photos/seed/mkt-sofa/120/80',
    meta: { price: '₹18,500', location: 'Tambaram' },
    priority: 8,
  },

  // Daily dose
  {
    featureKey: 'daily_dose',
    itemType: 'daily_link',
    title: 'Astrology',
    titleTamil: 'ராசி பலன்',
    icon: 'star',
    color: '#7c3aed',
    link: '/astrology',
    meta: { slug: 'astrology' },
    priority: 10,
  },
  {
    featureKey: 'daily_dose',
    itemType: 'daily_link',
    title: 'Daily Quiz',
    titleTamil: '5 கேள்வி',
    icon: 'quiz',
    color: '#2563eb',
    link: '/explore/news_quiz',
    meta: { slug: 'quiz' },
    priority: 9,
  },
  {
    featureKey: 'daily_dose',
    itemType: 'daily_link',
    title: 'Stock Watchlist',
    titleTamil: 'பங்குகள்',
    icon: 'chart',
    color: '#16a34a',
    link: '/explore/daily_dose',
    meta: { slug: 'stocks' },
    priority: 8,
  },
  {
    featureKey: 'daily_dose',
    itemType: 'daily_link',
    title: 'Today in History',
    titleTamil: 'வரலாற்றில் இன்று',
    icon: 'history',
    color: '#ea580c',
    link: '/explore/daily_dose',
    meta: { slug: 'history' },
    priority: 7,
  },
  {
    featureKey: 'daily_dose',
    itemType: 'daily_link',
    title: 'Random Game',
    titleTamil: 'விளையாட்டு',
    icon: 'game',
    color: '#db2777',
    link: '/explore/daily_dose',
    meta: { slug: 'game' },
    priority: 6,
  },

  // Local updates
  {
    featureKey: 'local_updates',
    itemType: 'local_status',
    title: 'Water Supply',
    titleTamil: 'தண்ணீர் விநியோகம்',
    icon: 'water',
    meta: { status: 'Normal', detail: 'On schedule' },
    priority: 10,
  },
  {
    featureKey: 'local_updates',
    itemType: 'local_status',
    title: 'Power Cut',
    titleTamil: 'மின்வெட்டு',
    icon: 'power',
    meta: { status: 'Clear', detail: 'No Power Cuts' },
    priority: 9,
  },
  {
    featureKey: 'local_updates',
    itemType: 'local_status',
    title: 'Metro Update',
    titleTamil: 'மெட்ரோ',
    icon: 'metro',
    meta: { status: 'Running', detail: 'All lines normal' },
    priority: 8,
  },
  {
    featureKey: 'local_updates',
    itemType: 'local_status',
    title: 'Air Quality',
    titleTamil: 'காற்றின் தரம்',
    icon: 'air',
    meta: { status: 'Moderate', detail: 'AQI 112' },
    priority: 7,
  },

  // Trending
  {
    featureKey: 'trending',
    itemType: 'trend',
    title: '#ChennaiRain',
    meta: { posts: 1240 },
    priority: 10,
  },
  {
    featureKey: 'trending',
    itemType: 'trend',
    title: '#GoldPrice',
    meta: { posts: 890 },
    priority: 9,
  },
  {
    featureKey: 'trending',
    itemType: 'trend',
    title: '#TNPSC',
    meta: { posts: 650 },
    priority: 8,
  },
  {
    featureKey: 'trending',
    itemType: 'trend',
    title: '#ChennaiMetro',
    meta: { posts: 420 },
    priority: 7,
  },

  // Community
  {
    featureKey: 'community_feed',
    itemType: 'community_post',
    title: 'Ramesh K',
    titleTamil: 'அண்ணா நகரில் இன்று மழை பெய்ய வாய்ப்பு உள்ளதா?',
    image: 'https://picsum.photos/seed/user-ramesh/48/48',
    meta: { likes: 24, comments: 8, postedAgo: '1 hour ago' },
    priority: 10,
  },
  {
    featureKey: 'community_feed',
    itemType: 'community_post',
    title: 'Kavitha M',
    titleTamil: 'வேளச்சேரியில் புதிய பூங்கா திறப்பு — அழகான இடம்!',
    image: 'https://picsum.photos/seed/user-kavitha/48/48',
    meta: { likes: 56, comments: 12, postedAgo: '3 hours ago' },
    priority: 9,
  },

  // Quiz sample questions
  {
    featureKey: 'news_quiz',
    itemType: 'quiz_question',
    title: 'Which city hosts the Chennai Metro?',
    meta: {
      options: ['Chennai', 'Madurai', 'Coimbatore', 'Salem'],
      answerIndex: 0,
    },
    priority: 10,
  },
  {
    featureKey: 'news_quiz',
    itemType: 'quiz_question',
    title: 'NIFTY 50 is related to which market?',
    meta: {
      options: ['Stock market', 'Gold market', 'Fuel prices', 'Weather'],
      answerIndex: 0,
    },
    priority: 9,
  },
];
